# Generated by Django 3.0.4 on 2025-02-02 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pvp',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=9, verbose_name='Precio de venta'),
        ),
    ]
